---
nginx_version: 3.30.0
nginx_repo_url: https://kubernetes.github.io/ingress-nginx

cert_manager_version: v1.3.1
cert_manager_repo_url: https://charts.jetstack.io

prometheus_stack_version: 15.4.6
prometheus_stack_repo_url: https://prometheus-community.github.io/helm-charts
